// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfload

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type DatapathDatapathParams struct {
	ProxyMark            uint32
	TargetIp             uint32
	ContainerPeerIfindex uint32
	ContainerIfindex     uint32
	SandboxLoIfindex     uint32
	SandboxPeerMac       [6]uint8
	Pad0                 [2]uint8
	ContainerMac         [6]uint8
	Pad1                 [2]uint8
}

// LoadDatapath returns the embedded CollectionSpec for Datapath.
func LoadDatapath() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DatapathBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Datapath: %w", err)
	}

	return spec, err
}

// LoadDatapathObjects loads Datapath and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DatapathObjects
//	*DatapathPrograms
//	*DatapathMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDatapathObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDatapath()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DatapathSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DatapathSpecs struct {
	DatapathProgramSpecs
	DatapathMapSpecs
}

// DatapathSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DatapathProgramSpecs struct {
	TcContainerEgress      *ebpf.ProgramSpec `ebpf:"tc_container_egress"`
	TcContainerIngress     *ebpf.ProgramSpec `ebpf:"tc_container_ingress"`
	TcContainerPeerIngress *ebpf.ProgramSpec `ebpf:"tc_container_peer_ingress"`
	TcSubSandboxIngress    *ebpf.ProgramSpec `ebpf:"tc_sub_sandbox_ingress"`
}

// DatapathMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DatapathMapSpecs struct {
	ParamsMap  *ebpf.MapSpec `ebpf:"params_map"`
	ProxyPorts *ebpf.MapSpec `ebpf:"proxy_ports"`
}

// DatapathObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDatapathObjects or ebpf.CollectionSpec.LoadAndAssign.
type DatapathObjects struct {
	DatapathPrograms
	DatapathMaps
}

func (o *DatapathObjects) Close() error {
	return _DatapathClose(
		&o.DatapathPrograms,
		&o.DatapathMaps,
	)
}

// DatapathMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDatapathObjects or ebpf.CollectionSpec.LoadAndAssign.
type DatapathMaps struct {
	ParamsMap  *ebpf.Map `ebpf:"params_map"`
	ProxyPorts *ebpf.Map `ebpf:"proxy_ports"`
}

func (m *DatapathMaps) Close() error {
	return _DatapathClose(
		m.ParamsMap,
		m.ProxyPorts,
	)
}

// DatapathPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDatapathObjects or ebpf.CollectionSpec.LoadAndAssign.
type DatapathPrograms struct {
	TcContainerEgress      *ebpf.Program `ebpf:"tc_container_egress"`
	TcContainerIngress     *ebpf.Program `ebpf:"tc_container_ingress"`
	TcContainerPeerIngress *ebpf.Program `ebpf:"tc_container_peer_ingress"`
	TcSubSandboxIngress    *ebpf.Program `ebpf:"tc_sub_sandbox_ingress"`
}

func (p *DatapathPrograms) Close() error {
	return _DatapathClose(
		p.TcContainerEgress,
		p.TcContainerIngress,
		p.TcContainerPeerIngress,
		p.TcSubSandboxIngress,
	)
}

func _DatapathClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed datapath_bpfel.o
var _DatapathBytes []byte
