// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package config

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PatchBodyContentsJsonType.
const (
	JSON PatchBodyContentsJsonType = "JSON"
)

// Valid indicates whether the value is a known member of the PatchBodyContentsJsonType enum.
func (e PatchBodyContentsJsonType) Valid() bool {
	switch e {
	case JSON:
		return true
	default:
		return false
	}
}

// Defines values for RawFileContentsType.
const (
	Contents RawFileContentsType = "Contents"
)

// Valid indicates whether the value is a known member of the RawFileContentsType enum.
func (e RawFileContentsType) Valid() bool {
	switch e {
	case Contents:
		return true
	default:
		return false
	}
}

// Defines values for RawFilePathType.
const (
	Path RawFilePathType = "Path"
)

// Valid indicates whether the value is a known member of the RawFilePathType enum.
func (e RawFilePathType) Valid() bool {
	switch e {
	case Path:
		return true
	default:
		return false
	}
}

// Defines values for ReplaceBodyContentsBase64Type.
const (
	BASE64 ReplaceBodyContentsBase64Type = "BASE64"
)

// Valid indicates whether the value is a known member of the ReplaceBodyContentsBase64Type enum.
func (e ReplaceBodyContentsBase64Type) Valid() bool {
	switch e {
	case BASE64:
		return true
	default:
		return false
	}
}

// Defines values for ReplaceBodyContentsTextType.
const (
	TEXT ReplaceBodyContentsTextType = "TEXT"
)

// Valid indicates whether the value is a known member of the ReplaceBodyContentsTextType enum.
func (e ReplaceBodyContentsTextType) Valid() bool {
	switch e {
	case TEXT:
		return true
	default:
		return false
	}
}

// Defines values for Target.
const (
	Request  Target = "Request"
	Response Target = "Response"
)

// Valid indicates whether the value is a known member of the Target enum.
func (e Target) Valid() bool {
	switch e {
	case Request:
		return true
	case Response:
		return true
	default:
		return false
	}
}

// Actions defines model for Actions.
type Actions struct {
	// Abort If true, terminate the request/response with a 502.
	Abort *bool `json:"abort,omitempty" yaml:"abort,omitempty"`

	// Delay Wait this long before continuing. Format is the `humantime`
	// crate's flavor: `"100ms"`, `"3s"`, `"1m30s"`, etc.
	Delay   *string        `json:"delay,omitempty" yaml:"delay,omitempty"`
	Patch   *PatchAction   `json:"patch,omitempty" yaml:"patch,omitempty"`
	Replace *ReplaceAction `json:"replace,omitempty" yaml:"replace,omitempty"`
}

// ChaosTproxyConfig Top-level config for chaos-tproxy.
type ChaosTproxyConfig struct {
	// IgnoreMark Packet mark to ignore in iptables rules. Currently unused.
	IgnoreMark *int32 `json:"ignore_mark,omitempty" yaml:"ignore_mark,omitempty"`

	// Interface Network interface. Currently unused.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Interface *string `json:"interface,omitempty" yaml:"interface,omitempty"`

	// ListenPort Proxy listen port. Kept for backwards compatibility; currently unused.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	ListenPort *int32 `json:"listen_port,omitempty" yaml:"listen_port,omitempty"`

	// ProxyMark `SO_MARK` set on upstream sockets opened by the proxy.
	// Used by the eBPF egress program to skip the proxy's own
	// forward traffic and avoid redirect loops.
	ProxyMark *int32 `json:"proxy_mark,omitempty" yaml:"proxy_mark,omitempty"`

	// ProxyPorts TCP destination ports the chaos-tproxy will proxy.
	ProxyPorts *[]int32 `json:"proxy_ports,omitempty" yaml:"proxy_ports,omitempty"`

	// Role If set, rules only fire when the connection's
	// (src_ip, dst_ip) matches the configured side.
	Role *Role `json:"role,omitempty" yaml:"role,omitempty"`

	// RouteTable Routing table ID. Currently unused.
	RouteTable *int32 `json:"route_table,omitempty" yaml:"route_table,omitempty"`

	// Rules Chaos rules, evaluated in declaration order.
	Rules *[]Rule `json:"rules,omitempty" yaml:"rules,omitempty"`

	// SafeMode Deprecated.
	SafeMode *bool `json:"safe_mode,omitempty" yaml:"safe_mode,omitempty"`

	// Tls TLS configuration for the proxy.
	Tls *TLSConfig `json:"tls,omitempty" yaml:"tls,omitempty"`
}

// PatchAction defines model for PatchAction.
type PatchAction struct {
	Body *PatchBody `json:"body,omitempty" yaml:"body,omitempty"`

	// Headers Headers to append. Each entry is a `[name, value]` pair;
	// duplicate names are allowed for headers like Cookie.
	Headers *[][]string `json:"headers,omitempty" yaml:"headers,omitempty"`

	// Queries Query parameters to append. Each entry is a `[key, value]`
	// pair; duplicate keys are intentionally allowed (e.g.
	// `foo=1&foo=2`), which is why this is an array of pairs
	// rather than a map.
	Queries *[][]string `json:"queries,omitempty" yaml:"queries,omitempty"`
}

// PatchBody defines model for PatchBody.
type PatchBody struct {
	Contents PatchBodyContents `json:"contents" yaml:"contents"`
}

// PatchBodyContents defines model for PatchBodyContents.
type PatchBodyContents struct {
	union json.RawMessage
}

// PatchBodyContentsJson defines model for PatchBodyContentsJson.
type PatchBodyContentsJson struct {
	Type PatchBodyContentsJsonType `json:"type" yaml:"type"`

	// Value JSON value (as a string). The proxy parses this and merges
	// it into the request/response body using RFC 7396 JSON
	// Merge Patch semantics.
	Value string `json:"value" yaml:"value"`
}

// PatchBodyContentsJsonType defines model for PatchBodyContentsJson.Type.
type PatchBodyContentsJsonType string

// RawFile defines model for RawFile.
type RawFile struct {
	union json.RawMessage
}

// RawFileContents defines model for RawFileContents.
type RawFileContents struct {
	Type RawFileContentsType `json:"type" yaml:"type"`

	// Value Raw file contents (base64-encoded in JSON/YAML).
	Value []byte `json:"value" yaml:"value"`
}

// RawFileContentsType defines model for RawFileContents.Type.
type RawFileContentsType string

// RawFilePath defines model for RawFilePath.
type RawFilePath struct {
	Type RawFilePathType `json:"type" yaml:"type"`

	// Value Absolute or relative path to the file on disk.
	Value string `json:"value" yaml:"value"`
}

// RawFilePathType defines model for RawFilePath.Type.
type RawFilePathType string

// ReplaceAction defines model for ReplaceAction.
type ReplaceAction struct {
	Body *ReplaceBody `json:"body,omitempty" yaml:"body,omitempty"`

	// Code Replace response status code. Ignored on Request rules.
	Code *int32 `json:"code,omitempty" yaml:"code,omitempty"`

	// Headers Replace (set) request/response header values.
	Headers *map[string]string `json:"headers,omitempty" yaml:"headers,omitempty"`

	// Method Replace request method. Ignored on Response rules.
	Method *string `json:"method,omitempty" yaml:"method,omitempty"`

	// Path Replace request path. Ignored on Response rules.
	Path *string `json:"path,omitempty" yaml:"path,omitempty"`

	// Queries Replace request query parameters with this map. Ignored on Response rules.
	Queries *map[string]string `json:"queries,omitempty" yaml:"queries,omitempty"`
}

// ReplaceBody defines model for ReplaceBody.
type ReplaceBody struct {
	Contents ReplaceBodyContents `json:"contents" yaml:"contents"`
}

// ReplaceBodyContents defines model for ReplaceBodyContents.
type ReplaceBodyContents struct {
	union json.RawMessage
}

// ReplaceBodyContentsBase64 defines model for ReplaceBodyContentsBase64.
type ReplaceBodyContentsBase64 struct {
	Type ReplaceBodyContentsBase64Type `json:"type" yaml:"type"`

	// Value Base64-encoded replacement body (decoded by the proxy at apply time).
	Value string `json:"value" yaml:"value"`
}

// ReplaceBodyContentsBase64Type defines model for ReplaceBodyContentsBase64.Type.
type ReplaceBodyContentsBase64Type string

// ReplaceBodyContentsText defines model for ReplaceBodyContentsText.
type ReplaceBodyContentsText struct {
	Type ReplaceBodyContentsTextType `json:"type" yaml:"type"`

	// Value Literal replacement body.
	Value string `json:"value" yaml:"value"`
}

// ReplaceBodyContentsTextType defines model for ReplaceBodyContentsText.Type.
type ReplaceBodyContentsTextType string

// Role defines model for Role.
type Role struct {
	union json.RawMessage
}

// RoleClient defines model for RoleClient.
type RoleClient struct {
	// Client Rule fires when the connection's source ip is in this list.
	Client []string `json:"Client" yaml:"Client"`
}

// RoleServer defines model for RoleServer.
type RoleServer struct {
	// Server Rule fires when the connection's destination ip is in this list.
	Server []string `json:"Server" yaml:"Server"`
}

// Rule defines model for Rule.
type Rule struct {
	Actions  Actions  `json:"actions" yaml:"actions"`
	Selector Selector `json:"selector" yaml:"selector"`

	// Target Whether this rule matches against the HTTP request or the response.
	Target Target `json:"target" yaml:"target"`
}

// Selector defines model for Selector.
type Selector struct {
	// Code Match only when the response status equals this. Ignored on Request rules.
	Code *int32 `json:"code,omitempty" yaml:"code,omitempty"`

	// Method HTTP method (GET / POST / …).
	Method *string `json:"method,omitempty" yaml:"method,omitempty"`

	// Path Wildcard glob against the request URI path. Syntax is the
	// `wildmatch` crate's flavor: `?` matches one char, `*`
	// matches zero-or-more chars. Case-sensitive.
	Path *string `json:"path,omitempty" yaml:"path,omitempty"`

	// Port Match only when the original-dst port equals this.
	Port *int32 `json:"port,omitempty" yaml:"port,omitempty"`

	// RequestHeaders Match only when every (name, value) pair appears in the request headers.
	RequestHeaders *map[string]string `json:"request_headers,omitempty" yaml:"request_headers,omitempty"`

	// ResponseHeaders Match only when every (name, value) pair appears in the response headers. Ignored on Request rules.
	ResponseHeaders *map[string]string `json:"response_headers,omitempty" yaml:"response_headers,omitempty"`
}

// TLSConfig defines model for TLSConfig.
type TLSConfig struct {
	// CaFile CA certificate. If absent, system roots are used.
	CaFile   *RawFile `json:"ca_file,omitempty" yaml:"ca_file,omitempty"`
	CertFile RawFile  `json:"cert_file" yaml:"cert_file"`
	KeyFile  RawFile  `json:"key_file" yaml:"key_file"`
}

// Target Whether this rule matches against the HTTP request or the response.
type Target string

// AsPatchBodyContentsJson returns the union data inside the PatchBodyContents as a PatchBodyContentsJson
func (t PatchBodyContents) AsPatchBodyContentsJson() (PatchBodyContentsJson, error) {
	var body PatchBodyContentsJson
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchBodyContentsJson overwrites any union data inside the PatchBodyContents as the provided PatchBodyContentsJson
func (t *PatchBodyContents) FromPatchBodyContentsJson(v PatchBodyContentsJson) error {
	v.Type = "JSON"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchBodyContentsJson performs a merge with any union data inside the PatchBodyContents, using the provided PatchBodyContentsJson
func (t *PatchBodyContents) MergePatchBodyContentsJson(v PatchBodyContentsJson) error {
	v.Type = "JSON"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PatchBodyContents) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t PatchBodyContents) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "JSON":
		return t.AsPatchBodyContentsJson()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t PatchBodyContents) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PatchBodyContents) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRawFilePath returns the union data inside the RawFile as a RawFilePath
func (t RawFile) AsRawFilePath() (RawFilePath, error) {
	var body RawFilePath
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRawFilePath overwrites any union data inside the RawFile as the provided RawFilePath
func (t *RawFile) FromRawFilePath(v RawFilePath) error {
	v.Type = "Path"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRawFilePath performs a merge with any union data inside the RawFile, using the provided RawFilePath
func (t *RawFile) MergeRawFilePath(v RawFilePath) error {
	v.Type = "Path"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRawFileContents returns the union data inside the RawFile as a RawFileContents
func (t RawFile) AsRawFileContents() (RawFileContents, error) {
	var body RawFileContents
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRawFileContents overwrites any union data inside the RawFile as the provided RawFileContents
func (t *RawFile) FromRawFileContents(v RawFileContents) error {
	v.Type = "Contents"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRawFileContents performs a merge with any union data inside the RawFile, using the provided RawFileContents
func (t *RawFile) MergeRawFileContents(v RawFileContents) error {
	v.Type = "Contents"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RawFile) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RawFile) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Contents":
		return t.AsRawFileContents()
	case "Path":
		return t.AsRawFilePath()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RawFile) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RawFile) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsReplaceBodyContentsText returns the union data inside the ReplaceBodyContents as a ReplaceBodyContentsText
func (t ReplaceBodyContents) AsReplaceBodyContentsText() (ReplaceBodyContentsText, error) {
	var body ReplaceBodyContentsText
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReplaceBodyContentsText overwrites any union data inside the ReplaceBodyContents as the provided ReplaceBodyContentsText
func (t *ReplaceBodyContents) FromReplaceBodyContentsText(v ReplaceBodyContentsText) error {
	v.Type = "TEXT"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReplaceBodyContentsText performs a merge with any union data inside the ReplaceBodyContents, using the provided ReplaceBodyContentsText
func (t *ReplaceBodyContents) MergeReplaceBodyContentsText(v ReplaceBodyContentsText) error {
	v.Type = "TEXT"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReplaceBodyContentsBase64 returns the union data inside the ReplaceBodyContents as a ReplaceBodyContentsBase64
func (t ReplaceBodyContents) AsReplaceBodyContentsBase64() (ReplaceBodyContentsBase64, error) {
	var body ReplaceBodyContentsBase64
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReplaceBodyContentsBase64 overwrites any union data inside the ReplaceBodyContents as the provided ReplaceBodyContentsBase64
func (t *ReplaceBodyContents) FromReplaceBodyContentsBase64(v ReplaceBodyContentsBase64) error {
	v.Type = "BASE64"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReplaceBodyContentsBase64 performs a merge with any union data inside the ReplaceBodyContents, using the provided ReplaceBodyContentsBase64
func (t *ReplaceBodyContents) MergeReplaceBodyContentsBase64(v ReplaceBodyContentsBase64) error {
	v.Type = "BASE64"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ReplaceBodyContents) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ReplaceBodyContents) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "BASE64":
		return t.AsReplaceBodyContentsBase64()
	case "TEXT":
		return t.AsReplaceBodyContentsText()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ReplaceBodyContents) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ReplaceBodyContents) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRoleClient returns the union data inside the Role as a RoleClient
func (t Role) AsRoleClient() (RoleClient, error) {
	var body RoleClient
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRoleClient overwrites any union data inside the Role as the provided RoleClient
func (t *Role) FromRoleClient(v RoleClient) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRoleClient performs a merge with any union data inside the Role, using the provided RoleClient
func (t *Role) MergeRoleClient(v RoleClient) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRoleServer returns the union data inside the Role as a RoleServer
func (t Role) AsRoleServer() (RoleServer, error) {
	var body RoleServer
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRoleServer overwrites any union data inside the Role as the provided RoleServer
func (t *Role) FromRoleServer(v RoleServer) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRoleServer performs a merge with any union data inside the Role, using the provided RoleServer
func (t *Role) MergeRoleServer(v RoleServer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Role) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Role) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
